version: "2.4"
services:
  backend:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
        - 7070:7070
    depends_on:
      - postgres

  postgres:
    container_name: db
    image: postgres:13.1
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: PINLOX!@#
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  nginx:
      image: nginx
      build: ./nginx
      restart: always
      ports:
        - 80:80
      depends_on:
        - flask

