version: "2.4"
services:
  backend:
    container_name: web
    build: ./web
    restart: always
    depends_on:
      - postgres
    ports:
        - 5000:5000

  postgres:
    container_name: db
    image: postgres:13.1
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: PINLOX!@#
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  nginx:
      image: nginx
      container_name: nginx
      build: ./nginx
      restart: always
      ports:
        - 80:80
      depends_on:
        - backend

