FROM python:3.7-slim

WORKDIR /web

ADD . /web

RUN pwd
RUN ls -la

RUN pwd
RUN ls -la app/

RUN apt-get update
RUN apt-get install -y build-essential python3-dev nano lsof

RUN pip install -r requirements.txt
RUN usermod --non-unique --uid 1000 www-data \
  && groupmod --non-unique --gid 1000 www-data \
  && chown -R www-data:www-data /web

ENV FLASK_RUN_HOST=0.0.0.0
#USER www-data

#CMD ["flask", "run"]
RUN pwd
CMD ["uwsgi", "--ini", "uwsgi.ini"]
